#!/bin/sh
set -eu

ROOT=$(CDPATH= cd -- "$(dirname "$0")/../.." && pwd)
SCRIPT="$ROOT/core-runtime/scripts/build-fbneo.sh"
WORKFLOW="$ROOT/.github/workflows/build-fbneo.yml"
LAUNCHER="$ROOT/core-runtime/launcher-3ds/fbneo_launcher.c"
LAUNCHER_BUILD="$ROOT/core-runtime/scripts/build-fbneo-launcher.sh"
test -x "$SCRIPT"
test -x "$LAUNCHER_BUILD"
test -f "$LAUNCHER"
grep -q 'libretro/FBNeo' "$WORKFLOW"
grep -q 'platform=ctr' "$SCRIPT"
grep -q 'SUBSET=all' "$SCRIPT"
grep -q 'IOAPI_NO_64' "$SCRIPT"
grep -q 'INCLUDE_CHD_SUPPORT=0' "$SCRIPT"
grep -q -- '-include wchar.h' "$SCRIPT"
grep -q "CFLAGS='-DIOAPI_NO_64'" "$SCRIPT"
grep -q "CXXFLAGS='-include wchar.h'" "$SCRIPT"
grep -q 'JOBS="\${JOBS:-1}"' "$SCRIPT"
grep -q -- '--output-sync=target' "$SCRIPT"
grep -q 'SPLIT_UP_LINK=1' "$SCRIPT"
grep -q 'arm-none-eabi-ar' "$SCRIPT"
grep -q 'OBJECTS_LINE=' "$SCRIPT"
grep -q 'fbneo-no-archive.mk' "$SCRIPT"
test -f "$ROOT/core-runtime/scripts/fbneo-no-archive.mk"
grep -q 'fbneo_objects' "$SCRIPT"
grep -q '\"\$AR\" rcs' "$SCRIPT"
grep -q '\"\$AR\" t' "$SCRIPT"
grep -q 'fbneo_all_libretro_ctr.a' "$SCRIPT"
grep -q 'build-fbneo-launcher.sh' "$SCRIPT"
grep -q 'retro_init' "$LAUNCHER"
grep -q 'retro_run' "$LAUNCHER"
grep -q '#include <3ds.h>' "$LAUNCHER"
grep -q 'gfxGetFramebuffer' "$LAUNCHER"
grep -q 'hidScanInput' "$LAUNCHER"
grep -q 'ndsp' "$LAUNCHER"
grep -q 'romfs:/content' "$LAUNCHER"
grep -q 'sdmc:/vcoven/saves' "$LAUNCHER"
if grep -q 'RetroArch' "$LAUNCHER_BUILD"; then
    printf '%s\n' 'launcher must not depend on RetroArch' >&2
    exit 1
fi
grep -q -- '--strip-debug' "$LAUNCHER_BUILD"
grep -q 'arm-none-eabi-readelf' "$LAUNCHER_BUILD"
grep -q 'vfs/vfs_implementation.c' "$LAUNCHER_BUILD"
grep -q 'streams/file_stream.c' "$LAUNCHER_BUILD"
grep -q 'Class:' "$SCRIPT"
grep -q '16 \* 1024 \* 1024' "$SCRIPT"
grep -q '2fcb2628fbfd529806e75f3559a9d82758c8a5cc' "$SCRIPT"
printf '%s\n' 'FBNeo 3DS build contract passed.'
